apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-resources
  labels:
    demo: k8s-handson
spec:
  containers:
  - name: nginx-server
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m

# describe fields shows the resources and qos field turns into bustable
# bustable/garenteed/ - besteffort