apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hostname-app-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hostname-app
    spec:
      containers:
      - name: hostname-app
        image: hostname-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
  progressDeadlineSeconds: 100
  minReadySeconds: 10
  strategy:
    type: Recreate