apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-command
  labels:
    demo: k8s-handson
spec:
  containers:
  - name: liveness-probe-command
    image: k8s.gcr.io/busybox
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 15; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5