apiVersion: v1
kind: Pod
metadata:
  name: secrets-vol-demo
  labels:
    demo: k8s-handson
spec:
  containers:
    - name: secrets-vol-demo
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: aws-credentials-volume
          mountPath: /etc/aws-credentials
  volumes:
    - name: aws-credentials-volume
      secret:
        secretName: aws-credentials