apiVersion: v1
kind: Pod
metadata:
  name: secrets-env-demo
  labels:
    demo: k8s-handson
spec:
  containers:
  - name: secrets-env-demo
    image: nginx
    imagePullPolicy: IfNotPresent
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: aws_secret_access_key