apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels:
    demo: k8s-handson
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - name: security-context-demo
    image: hostname-app:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false