apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  labels:
    demo: k8s-handson
spec:
  containers:
  - name: cpu-demo
    image: vish/stress
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"