apiVersion: v1
kind: Pod
metadata:
  name: node-aff
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-label
            operator: In
            value: 
            - node-label
  containters:
  - name: node-aff
    image: nginx

